"""Board-tracking practice tasks, generated by code in unlimited quantity (always correct).

Motivation: LLMs score ~0% on predicting the board after a move sequence (arXiv 2507.00726), and
calculating a tactic is exactly that. These tasks train it directly:
  board   "after these moves, write the board"            -> 8-line diagram
  square  "after these moves, what is on e5, g7, d1?"     -> one answer per square
Lines come from real tactics: the puzzle's solution, Stockfish's candidate lines, or random legal play.

Usage: .venv/bin/python aux_tasks.py --puzzles pool_train1.jsonl --n 4000 --out results/sft/aux_4k.jsonl
       [--analysis FILE] [--exclude pool_pilot2k.jsonl]
"""
import argparse
import json
import random

import chess

from perception import board_diagram


def san_line(board, ucis):
    b, out = board.copy(), []
    for u in ucis:
        m = chess.Move.from_uci(u)
        out.append(b.san(m))
        b.push(m)
    return out, b


def random_line(board, rng, k):
    b, ucis = board.copy(), []
    for _ in range(k):
        moves = list(b.legal_moves)
        if not moves:
            break
        # prefer forcing moves half the time, like a tactical calculation would
        forcing = [m for m in moves if b.is_capture(m) or b.gives_check(m)]
        m = rng.choice(forcing if forcing and rng.random() < 0.5 else moves)
        ucis.append(m.uci())
        b.push(m)
    return ucis


def make_task(p, rng, analysis=None):
    board = chess.Board(p["fen"])
    src = rng.random()
    if src < 0.4:
        ucis = p["full_solution"][: rng.randint(1, len(p["full_solution"]))]
    elif src < 0.7 and analysis:
        c = rng.choice(analysis["candidates"])
        ucis = c["line_uci"][: rng.randint(1, len(c["line_uci"]))]
    else:
        ucis = random_line(board, rng, rng.randint(1, 6))
    if not ucis:
        return None
    sans, after = san_line(board, ucis)
    moves_txt = " ".join(sans)
    head = [f"Position (FEN): {p['fen']}",
            "Board (White pieces uppercase, Black pieces lowercase; rank 8 at the top):",
            board_diagram(board), "", f"Moves played from this position: {moves_txt}"]
    if rng.random() < 0.5:
        prompt = "\n".join(head + ["", "Write the board after these moves, in the same diagram format."])
        target = board_diagram(after)
    else:
        changed = [s for s in chess.SQUARES if board.piece_at(s) != after.piece_at(s)]
        other = [s for s in chess.SQUARES if s not in changed]
        sqs = rng.sample(changed, min(len(changed), 2)) + rng.sample(other, 1)
        rng.shuffle(sqs)
        names = ", ".join(chess.square_name(s) for s in sqs)
        prompt = "\n".join(head + ["", f"After these moves, what stands on each of these squares: {names}?"])

        def what(s):
            pc = after.piece_at(s)
            return "empty" if pc is None else f"{'White' if pc.color else 'Black'} {chess.piece_name(pc.piece_type)}"
        target = "\n".join(f"{chess.square_name(s)}: {what(s)}" for s in sqs)
    return {"puzzle_id": p["puzzle_id"], "task": "aux", "prompt": prompt, "target": target}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--puzzles", required=True)
    ap.add_argument("--n", type=int, required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--analysis", default=None)
    ap.add_argument("--exclude", nargs="*", default=[])
    ap.add_argument("--seed", type=int, default=5)
    args = ap.parse_args()
    rng = random.Random(args.seed)
    excl = {json.loads(l)["puzzle_id"] for f in args.exclude for l in open(f)}
    pz = [json.loads(l) for l in open(args.puzzles)]
    pz = [p for p in pz if p["puzzle_id"] not in excl]
    an = {json.loads(l)["puzzle_id"]: json.loads(l) for l in open(args.analysis)} if args.analysis else {}
    rng.shuffle(pz)
    n = 0
    with open(args.out, "w") as f:
        for p in pz:
            t = make_task(p, rng, an.get(p["puzzle_id"]))
            if t:
                f.write(json.dumps(t) + "\n")
                n += 1
            if n >= args.n:
                break
    print(f"wrote {n} aux tasks to {args.out}")


if __name__ == "__main__":
    main()
